/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author hp
 */
public class PanelAgregarCupon extends javax.swing.JFrame {

    /**
     * Creates new form PanelAgragraCupon
     */
    public PanelAgregarCupon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAgregaCupon = new javax.swing.JLabel();
        LblBeneficio = new javax.swing.JLabel();
        LblBeneficio1 = new javax.swing.JLabel();
        jTxtFldIDCupon = new javax.swing.JTextField();
        LblBeneficio2 = new javax.swing.JLabel();
        LblElegibleRespuesta = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        BtnNoTengo = new javax.swing.JButton();
        BtnVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(216, 162, 60));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));

        PanelFondo.setBackground(new java.awt.Color(216, 162, 60));

        jPanel1.setBackground(new java.awt.Color(183, 76, 59));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        LblTitulo.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(1, 114, 160));
        LblTitulo.setText("Agrega tu cupón: ");

        LblAgregaCupon.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblAgregaCupon.setForeground(new java.awt.Color(152, 4, 4));
        LblAgregaCupon.setText("Agrega tu cupón: ");

        LblBeneficio.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblBeneficio.setForeground(new java.awt.Color(152, 4, 4));
        LblBeneficio.setText("Beneficio:");

        LblBeneficio1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblBeneficio1.setForeground(new java.awt.Color(152, 4, 4));
        LblBeneficio1.setText("Elegible:");

        jTxtFldIDCupon.setBackground(new java.awt.Color(1, 114, 160));
        jTxtFldIDCupon.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jTxtFldIDCupon.setText("ID cupon");
        jTxtFldIDCupon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblBeneficio2.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblBeneficio2.setForeground(new java.awt.Color(152, 4, 4));
        LblBeneficio2.setText("Beneficio");

        LblElegibleRespuesta.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        LblElegibleRespuesta.setForeground(new java.awt.Color(152, 4, 4));
        LblElegibleRespuesta.setText("si/no");

        BtnAtras.setBackground(new java.awt.Color(152, 4, 4));
        BtnAtras.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        BtnAtras.setText("Atras");
        BtnAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnNoTengo.setBackground(new java.awt.Color(152, 4, 4));
        BtnNoTengo.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        BtnNoTengo.setText("No tengo Cupon");
        BtnNoTengo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnVerificar.setBackground(new java.awt.Color(152, 4, 4));
        BtnVerificar.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        BtnVerificar.setText("Varificar");
        BtnVerificar.setActionCommand("Verificar");
        BtnVerificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(LblTitulo))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addComponent(LblBeneficio)
                                .addGap(31, 31, 31)
                                .addComponent(LblBeneficio2))
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addComponent(LblAgregaCupon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtFldIDCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addComponent(LblBeneficio1)
                                .addGap(35, 35, 35)
                                .addComponent(LblElegibleRespuesta)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BtnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BtnNoTengo)
                .addGap(103, 103, 103))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LblTitulo)
                .addGap(26, 26, 26)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAgregaCupon)
                    .addComponent(jTxtFldIDCupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBeneficio)
                    .addComponent(LblBeneficio2))
                .addGap(50, 50, 50)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBeneficio1)
                    .addComponent(LblElegibleRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtras)
                    .addComponent(BtnNoTengo)
                    .addComponent(BtnVerificar))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAgregarCupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAgregarCupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAgregarCupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAgregarCupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAgregarCupon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnNoTengo;
    private javax.swing.JButton BtnVerificar;
    private javax.swing.JLabel LblAgregaCupon;
    private javax.swing.JLabel LblBeneficio;
    private javax.swing.JLabel LblBeneficio1;
    private javax.swing.JLabel LblBeneficio2;
    private javax.swing.JLabel LblElegibleRespuesta;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtFldIDCupon;
    // End of variables declaration//GEN-END:variables
}
