/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import negocio.BOs.UsuarioBO;
import negocio.DTOs.UsuarioNuevoDTO;
import negocio.excepciones.NegocioException;
import persistencia.DAOs.IUsuarioDAO;
import persistencia.DAOs.UsuarioDAO;
import persistencia.conexion.ConexionBD;
import persistencia.dominio.Usuario;

/**
 *
 * @author maria
 */
public class PanelRegistroUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroUsuario
     */
    public PanelRegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(153, 0, 0));

        label1.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        label1.setText("Usuario:");

        label2.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        label2.setText("Contraseña:");

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.setActionCommand("InicioSesion");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        jButton2.setText("Continuar como Invitado");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTextField1.setBackground(new java.awt.Color(0, 102, 153));

        jPasswordField1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String correoU = jTextField1.getText();
        String contra = new String(jPasswordField1.getPassword());
        if (correoU == null || correoU.isBlank() || correoU.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El usuario no puede estar vacío.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (contra == null || contra.isBlank() || contra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        UsuarioNuevoDTO usuario = new UsuarioNuevoDTO(correoU, contra);
        try {
            Usuario u = usuarioBO.validarUsuario(usuario);
            if(u == null){
                JOptionPane.showMessageDialog(this, "No se encontró al usuario.", "Credenciales equivocadas", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (u != null) {
                Window ventana = SwingUtilities.getWindowAncestor(this);
    
                if (ventana instanceof JFrame) {
                JFrame framePrincipal = (JFrame) ventana;

                PanelRealizarPedidoCliente nuevoPanel = new PanelRealizarPedidoCliente();

                framePrincipal.getContentPane().removeAll();
                framePrincipal.getContentPane().add(nuevoPanel);

                framePrincipal.revalidate();
                framePrincipal.repaint();
                }
            }
        } catch (NegocioException ne) {
            JOptionPane.showMessageDialog(this, "Error al encontrar el usuario.", "Error en la base de datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Window ventana = SwingUtilities.getWindowAncestor(this);

        if (ventana instanceof JFrame) {
            JFrame framePrincipal = (JFrame) ventana;

            PanelRealizarPedidoCliente nuevoPanel = new PanelRealizarPedidoCliente();

            framePrincipal.getContentPane().removeAll();
            framePrincipal.getContentPane().add(nuevoPanel);

            framePrincipal.revalidate();
            framePrincipal.repaint();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
    private final UsuarioBO usuarioBO = new UsuarioBO(new UsuarioDAO(new ConexionBD()));

} 

